[package]
name = "pub_iec"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pnet = "0.35.0"
crc32fast = "1.4.2"
chrono = "0.4.38"
